### ISSUE TITLE
Context Aware Enhancer not restricted to exact match

### ISSUE THREAD

**Issue by dhruvmullick** [microsoft/presidio#989] opened 2022-12-27 22:32 UTC
https://github.com/microsoft/presidio/blob/a29e1bb9f8b20a9700e44f83582576d884779260/presidio-analyzer/presidio_analyzer/context_aware_enhancers/lemma_context_aware_enhancer.py#L157

This method is supposed to be for exact matches, but the code here implies it considers [substrings](https://github.com/microsoft/presidio/blob/a29e1bb9f8b20a9700e44f83582576d884779260/presidio-analyzer/presidio_analyzer/context_aware_enhancers/lemma_context_aware_enhancer.py#L178) as well.

**Comment by omri374** [comment] 2023-05-01 09:18
Duplicate of #1061

**Closed by omri374** 2023-05-01 09:18 UTC
