### ISSUE TITLE
Anonymizer does not work 

### ISSUE THREAD

**Issue by Siddhartha90** [microsoft/presidio#1281] opened 2024-02-08 03:46 UTC
**Describe the bug**

`test data 630-596-1111`

redacts ok to give back `test data`

but `test data 630-596-1111`

does not redact the phone number.

**To Reproduce**

```

try:
    nlp = spacy.load("en_core_web_lg")
except OSError:
    # Model not found, download it
    spacy.cli.download("en_core_web_lg")
    nlp = spacy.load("en_core_web_lg")

analyzer = AnalyzerEngine()
anonymizer = AnonymizerEngine()

analyzer_results = analyzer.analyze(
    text=text_to_anonymize,
    entities=["PHONE_NUMBER", "EMAIL_ADDRESS", "URL", "LOCATION"],
    language="en",
)
scrubbed_text = anonymizer.anonymize(
    text=text_to_anonymize,
    analyzer_results=analyzer_results,
    operators={"DEFAULT": OperatorConfig("redact", {})},
).text

print(scrubbed_text)

```

**Expected behavior**
Phone number gets scrubbed.

I'm on

**presidio-analyzer==2.2.351
presidio-anonymizer==2.2.351**

**Comment by VMD7** [comment] 2024-02-08 05:27
Hi @Siddhartha90 
I have verified your code with mentioned versions, its working as expected. It successfully redacting the phone number. Please check your spacy model, does it modified or trained by something. You can also verify the same on demo site as well, here its link - https://huggingface.co/spaces/presidio/presidio_demo

**Comment by omri374** [comment] 2024-02-08 09:00
@Siddhartha90 can you please provide a reproducible example? Both samples seem identical.

**Comment by omri374** [comment] 2024-02-13 15:04
Closing for now, please re-open if needed.

**Closed by omri374** 2024-02-13 15:04 UTC

**Comment by Siddhartha90** [comment] 2024-02-16 18:24
@VMD7 @omri374 Apologies, i updated the description with the correct example

**Comment by VMD7** [comment] 2024-02-23 05:11
Hi @Siddhartha90 
Thanks for your response. Actually the problem is not with the anonymizer or analyzer engine. The main problem lies in the model we are using to predict the entity. You can try with little larger models such as "stanford-deidentifier-base" or "deid_roberta_i2b2". You can experiment with different models and use according to your need. If you wanna use spacy model only then you can train or finetune the spacy model with these kind of examples and use the same, you will get results as expected.
