### ISSUE TITLE
ValueError: [E866] Expected a string or 'Doc' as input, but got: <class 'list'>.

### ISSUE THREAD

**Issue by tiagonmas** [microsoft/presidio#816] opened 2022-01-19 16:16 UTC
**Describe the bug**
I Tweaked the provided sample to load the string from a file, and I got the error below.

```
Traceback (most recent call last):
  File "C:\Users\tiagoand\source\repos\presidio.py", line 19, in <module>
    results = analyzer.analyze(text=text,
  File "C:\Users\tiagoand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\presidio_analyzer\analyzer_engine.py", line 163, in analyze
    nlp_artifacts = self.nlp_engine.process_text(text, language)
  File "C:\Users\tiagoand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\presidio_analyzer\nlp_engine\spacy_nlp_engine.py", line 43, in process_text
    doc = self.nlp[language](text)
  File "C:\Users\tiagoand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spacy\language.py", line 1002, in __call__
    doc = self._ensure_doc(text)
  File "C:\Users\tiagoand\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\spacy\language.py", line 1093, in _ensure_doc
    raise ValueError(Errors.E866.format(type=type(doc_like)))
ValueError: [E866] Expected a string or 'Doc' as input, but got: <class 'list'>.
```

**To Reproduce**
1. Run the code below

```
from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine

# text="My phone number is 212-555-5555"

with open ("doar2.csv", "r", encoding="utf-8") as myfile:
    text=myfile.readlines()
    

print(text)

print("\nNext")

# Set up the engine, loads the NLP module (spaCy model by default) 
# and other PII recognizers
analyzer = AnalyzerEngine()

# Call analyzer to get results
results = analyzer.analyze(text=text,
                           entities=["PHONE_NUMBER"],
                           language='en')
print(results)
```

**Expected behavior**
The list of PII entities

**Additional context**
I'm running this against a 2MB of a csv file that is an export of github issues and it's comments.

**Comment by omri374** [comment] 2022-01-19 19:17
Hi @tiagonmas, thanks for reaching out.

I believe the issue is with `f.readlines()` returning a list of strings while the Presidio Analyzer expects a string. You could either call `analyzer.analyze` in a loop, or see the example we have on [reading a csv](https://microsoft.github.io/presidio/samples/python/batch_processing/).

How this helps, please reach out if this doesn't solve your issue.

**Comment by omri374** [comment] 2022-02-02 09:33
Closing the issue, please re-open if needed.

**Closed by omri374** 2022-02-02 09:33 UTC
