### ISSUE TITLE
NER not working when the format  Name: David JName: David J

### ISSUE THREAD

**Issue by jems25** [microsoft/presidio#323] opened 2020-05-06 14:26 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://presidio-demo.azurewebsites.net/
2. Paste: in Input text text Box
IP: 192.168.0.1
    Name: David J

Anonymized text comes has

IP: <IP_ADDRESS>
    Name: David J

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/62078620/81188940-9cd07500-8fd3-11ea-8288-93074aab5776.png)

**Comment by omri374** [comment] 2020-05-06 18:18
Hi @jems25, looks like the issue is actually with the IBAN recognizer and not with the NER. If you paste only this:
IP: 192.168.0.1
Name: David J

It does work. The actual issue is probably with the IBAN recognizer. I'll open a different issue on this one.

**Comment by navalev** [comment] 2020-05-19 11:49
Hi @jems25. We are unable to reporduce the issue you decribed. Could you please include the steps to reprodue this?

**Comment by omri374** [comment] 2020-06-23 08:16
Closing for now, feel free to open if you have more information to share with us.

**Closed by omri374** 2020-06-23 08:16 UTC
