### ISSUE TITLE
Context word is recognized as entity in Pattern Recognizer

### ISSUE THREAD

**Issue by rayliu2007** [microsoft/presidio#909] opened 2022-08-23 22:57 UTC
**Describe the bug**
When using patternrecogninzer with context, if regex matches context word too, then context work itself is recognized as entity too. But it should not.

**Comment by omri374** [comment] 2022-08-24 06:23
Not sure I understand the issue. If a regex falsely detects a word as entity, then the issue is probably with the regex. Isn't it? Is the issue that the same word isn't used as context in addition to being an entity?

**Comment by omri374** [comment] 2022-10-02 11:33
Closing for now, please re-open if needed.

**Closed by omri374** 2022-10-02 11:33 UTC
