### ISSUE TITLE
Is ORGANIZATION entity type deprecated ?

### ISSUE THREAD

**Issue by Gojo1729** [microsoft/presidio#1242] opened 2023-12-28 19:14 UTC
Hello,
I've been using presidio analyzer as directed here - https://github.com/microsoft/presidio-research/blob/master/notebooks/4_Evaluate_Presidio_Analyzer.ipynb but I'm not able to detect "ORGANIZATION" entity type, is this deprecated ?

example input template
```
     {
        "full_text": "Juljan Lančič\nFactset\n8758 1780 Hemlock Lane Apt. 573\nSVENSHÖGEN\n, nan\n Sweden 34795\n",
        "masked": "{{PERSON}}\n{{ORGANIZATION}}\n{{STREET_ADDRESS}}\n",
        "spans": [
            {
                "entity_type": "STREET_ADDRESS",
                "entity_value": "8758 1780 Hemlock Lane Apt. 573\nSVENSHÖGEN\n, nan\n Sweden 34795",
                "start_position": 22,
                "end_position": 84
            },
            {
                "entity_type": "ORGANIZATION",
                "entity_value": "Factset",
                "start_position": 14,
                "end_position": 21
            },
            {
                "entity_type": "PERSON",
                "entity_value": "Juljan Lančič",
                "start_position": 0,
                "end_position": 13
            }
        ],
        "template_id": 110,
        "metadata": null
    }
```

Sample usage - 
`model.predict(InputSample("Juljan Lančič\nFactset\n8758 1780 Hemlock Lane Apt. 573\nSVENSHÖGEN\n, nan\n Sweden 34795\n"))`

Predicted labels - 
```
['PERSON',
 'PERSON',
 'PERSON',
 'PERSON',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'O',
 'PERSON',
 'PERSON',
 'O',
 'DATE_TIME',
 'O']
```

Presidio analyzer version - 2.2.351
presidio evaluator version - 0.1.1

**Comment by omri374** [comment] 2023-12-31 10:06
There's a n new configuration for NER in Presidio. Please check out the new notebooks (https://github.com/microsoft/presidio-research/blob/master/notebooks/4_Evaluate_Presidio_Analyzer.ipynb) for updated samples on how to define which entities should be returned by the model.

This change was needed as there are many types of PII detection models, each outputting different entity names (ORG vs ORGANIZATION, PERSON vs PER etc.) or having different error rates (ORGANIZATION in en_core_web_lg for example is quite bad, but with other transformers based models it is much better).

**Comment by omri374** [comment] 2023-12-31 10:06
Closing for now, please re-open if the problem isn't solved.

**Closed by omri374** 2023-12-31 10:06 UTC

**Comment by Gojo1729** [comment] 2024-01-02 06:37
@omri374 Which model should we genrally use for the NLPEngine ?
