### ISSUE TITLE
faker SerializationError, RecursionError

### ISSUE THREAD

**Issue by OlegBEZb** [microsoft/presidio#741] opened 2021-07-07 11:50 UTC
Good afternoon!

I was trying to reproduce [lambda functions with fake](https://github.com/microsoft/presidio/blob/main/docs/samples/python/example_custom_lambda_anonymizer.py) on [databricks](https://github.com/microsoft/presidio/blob/main/docs/samples/deployments/spark/notebooks/01_transform_presidio.py). 

I have added several pattern recognizers, configured the model (it's another question why spacy trf model can not be serialized as recommended [here](https://github.com/microsoft/presidio/issues/670#issuecomment-822190134)) and added a list of operators:
`fake_operators = {
    "PERSON": OperatorConfig("custom", {"lambda": lambda x: fake.name()}),
    "MY_NAME_IS": OperatorConfig("custom", {"lambda": lambda x: "name is " + fake.name()}),
    "PHONE_NUMBER": OperatorConfig("custom", {"lambda": lambda x: fake.phone_number()}),
    "EMAIL_ADDRESS": OperatorConfig("custom", {"lambda": lambda x: fake.email()})
}`

While applying udf from the example, I receive the following exception:

`pyspark.serializers.SerializationError: Caused by Traceback (most recent call last):
  File "/databricks/spark/python/pyspark/serializers.py", line 165, in _read_with_length
    return self.loads(obj)
  File "/databricks/spark/python/pyspark/serializers.py", line 469, in loads
    return pickle.loads(obj, encoding=encoding)
  File "/databricks/python/lib/python3.8/site-packages/faker/proxy.py", line 277, in __getattr__
    obj = getattr(self._proxy, name)
  File "/databricks/python/lib/python3.8/site-packages/faker/proxy.py", line 277, in __getattr__
    obj = getattr(self._proxy, name)
  File "/databricks/python/lib/python3.8/site-packages/faker/proxy.py", line 277, in __getattr__
    obj = getattr(self._proxy, name)
  [Previous line repeated 984 more times]
RecursionError: maximum recursion depth exceeded`

spacy model: en_core_web_lg
darabricks runtime: both 8.2 (includes Apache Spark 3.1.1, Scala 2.12) and 8.1 (includes Apache Spark 3.1.1, Scala 2.12)
faker: 8.9.1

It is possible to serialize faker functions to udfs separately but I'm not sure about their integration to the presidio at the moment.

Thank you for the help in advance!

**Comment by omri374** [comment] 2021-07-08 11:41
Hi @OlegBEZb, the faker integration is a sample and not fully supported. It seems like the issue is with serializing faker objects, and not Presidio's. The integration into Presidio is mainly for generating a fake value for replacement instead of a constant one.

**Comment by OlegBEZb** [comment] 2021-07-09 12:35
Hi @omri374!)

After a deeper investigation, I concluded with the same idea - the problem is not on Presidio's side. I have opened an issue in the Faker repo https://github.com/joke2k/faker/issues/1479. I hope this may help people who will use Presidio with Faker together.

**Comment by navalev** [comment] 2021-07-11 07:37
thank you @OlegBEZb! Closing the issue for now.

**Closed by navalev** 2021-07-11 07:37 UTC
